name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - name: Install Crystal
        uses: oprypin/install-crystal@v1
        with:
          crystal: 0.36.0

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: shards install

      - name: Run tests
        run: crystal spec
