name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: 0 21 * * *

jobs:
  quality:
    runs-on: ubuntu-20.04

    steps:
      - name: Install Crystal
        uses: oprypin/install-crystal@v1
        with:
          crystal: 0.36.1

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check code formatting
        run: crystal tool format --check

      - name: Install dependencies
        run: shards install

      - name: Crystal Ameba Linter
        run: shards build && ./bin/ameba 

      - name: Run tests
        run: crystal spec
